package:
  format-version: "1.0.0"
  name: "csp_apps_sama7d65"
  version: "v3.0.0"
  type: "application"
  status: "production"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.19.0"
